'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Side = exports.Main = exports.Group = undefined;

var _utils = require('../utils');

var styles = {
  'u-p-0': 'styles__u-p-0___2HB4H',
  'u-pt-0': 'styles__u-pt-0___2-qRh',
  'u-pb-0': 'styles__u-pb-0___yBQHm',
  'u-pl-0': 'styles__u-pl-0___2EZqZ',
  'u-pr-0': 'styles__u-pr-0___26hOP',
  'u-pv-0': 'styles__u-pv-0___1icCv',
  'u-ph-0': 'styles__u-ph-0___CQkHk',
  'u-p-1': 'styles__u-p-1___3NWXl',
  'u-pt-1': 'styles__u-pt-1___3OREU',
  'u-pb-1': 'styles__u-pb-1___3-IUY',
  'u-pl-1': 'styles__u-pl-1___3qtIl',
  'u-pr-1': 'styles__u-pr-1___Ytt-k',
  'u-pv-1': 'styles__u-pv-1___1DHzQ',
  'u-ph-1': 'styles__u-ph-1___SYbXW',
  'u-p-2': 'styles__u-p-2___JeNEw',
  'u-pt-2': 'styles__u-pt-2___1dCxG',
  'u-pb-2': 'styles__u-pb-2___2U4FP',
  'u-pl-2': 'styles__u-pl-2___22qbU',
  'u-pr-2': 'styles__u-pr-2___3sNK7',
  'u-pv-2': 'styles__u-pv-2___2tcyY',
  'u-ph-2': 'styles__u-ph-2___LcOKB',
  'u-p-3': 'styles__u-p-3___10uON',
  'u-pt-3': 'styles__u-pt-3___Gj1Cy',
  'u-pb-3': 'styles__u-pb-3___2sWEE',
  'u-pl-3': 'styles__u-pl-3___25VR9',
  'u-pr-3': 'styles__u-pr-3___A0-8V',
  'u-pv-3': 'styles__u-pv-3___RbdgB',
  'u-ph-3': 'styles__u-ph-3___3eqtt',
  'u-p-half': 'styles__u-p-half___ePG__',
  'u-pt-half': 'styles__u-pt-half___3A8rK',
  'u-pb-half': 'styles__u-pb-half___hkhG8',
  'u-pl-half': 'styles__u-pl-half___361hQ',
  'u-pr-half': 'styles__u-pr-half___xgx9V',
  'u-pv-half': 'styles__u-pv-half___oaWz3',
  'u-ph-half': 'styles__u-ph-half___3yokr',
  'u-p-1-half': 'styles__u-p-1-half___3McI1',
  'u-pt-1-half': 'styles__u-pt-1-half___3uwfA',
  'u-pb-1-half': 'styles__u-pb-1-half___2bmHS',
  'u-pl-1-half': 'styles__u-pl-1-half___1kf63',
  'u-pr-1-half': 'styles__u-pr-1-half___2JUiy',
  'u-pv-1-half': 'styles__u-pv-1-half___pFIln',
  'u-ph-1-half': 'styles__u-ph-1-half___3X8qk',
  'u-p-2-half': 'styles__u-p-2-half___3ej5M',
  'u-pt-2-half': 'styles__u-pt-2-half___12om2',
  'u-pb-2-half': 'styles__u-pb-2-half___2uf9v',
  'u-pl-2-half': 'styles__u-pl-2-half___140b3',
  'u-pr-2-half': 'styles__u-pr-2-half___1490I',
  'u-pv-2-half': 'styles__u-pv-2-half___3S2KC',
  'u-ph-2-half': 'styles__u-ph-2-half___1_it8',
  'u-m-0': 'styles__u-m-0___1t8r7',
  'u-mt-0': 'styles__u-mt-0___2NA_q',
  'u-mb-0': 'styles__u-mb-0___3YnZ9',
  'u-ml-0': 'styles__u-ml-0___1bmVF',
  'u-mr-0': 'styles__u-mr-0___3JuqS',
  'u-mv-0': 'styles__u-mv-0___1HVus',
  'u-mh-0': 'styles__u-mh-0___36Ksi',
  'u-m-1': 'styles__u-m-1___2xv-o',
  'u-mt-1': 'styles__u-mt-1___s7Y8V',
  'u-mb-1': 'styles__u-mb-1___257cX',
  'u-ml-1': 'styles__u-ml-1___3LsdY',
  'u-mr-1': 'styles__u-mr-1___YVFYM',
  'u-mv-1': 'styles__u-mv-1___24e99',
  'u-mh-1': 'styles__u-mh-1___pNzzX',
  'u-m-2': 'styles__u-m-2___3pAgk',
  'u-mt-2': 'styles__u-mt-2___DCp54',
  'u-mb-2': 'styles__u-mb-2___20gQY',
  'u-ml-2': 'styles__u-ml-2___12arC',
  'u-mr-2': 'styles__u-mr-2___7Ve5g',
  'u-mv-2': 'styles__u-mv-2___1lyiq',
  'u-mh-2': 'styles__u-mh-2___1Ww88',
  'u-m-3': 'styles__u-m-3___3Cm0K',
  'u-mt-3': 'styles__u-mt-3___2U7tf',
  'u-mb-3': 'styles__u-mb-3___GFhQM',
  'u-ml-3': 'styles__u-ml-3___3R2KA',
  'u-mr-3': 'styles__u-mr-3___Iq2mr',
  'u-mv-3': 'styles__u-mv-3___13t41',
  'u-mh-3': 'styles__u-mh-3___1PIVL',
  'u-m-half': 'styles__u-m-half___34ZnG',
  'u-mt-half': 'styles__u-mt-half___3Fc-L',
  'u-mb-half': 'styles__u-mb-half___2SX-i',
  'u-ml-half': 'styles__u-ml-half___2NsQb',
  'u-mr-half': 'styles__u-mr-half___2CmrU',
  'u-mv-half': 'styles__u-mv-half___GjVN6',
  'u-mh-half': 'styles__u-mh-half___3llBA',
  'u-m-1-half': 'styles__u-m-1-half___1Q3ht',
  'u-mt-1-half': 'styles__u-mt-1-half___2sjBd',
  'u-mb-1-half': 'styles__u-mb-1-half___3LQJl',
  'u-ml-1-half': 'styles__u-ml-1-half___sdspY',
  'u-mr-1-half': 'styles__u-mr-1-half___34NZs',
  'u-mv-1-half': 'styles__u-mv-1-half___3-idy',
  'u-mh-1-half': 'styles__u-mh-1-half___3IHY2',
  'u-m-2-half': 'styles__u-m-2-half___btLcd',
  'u-mt-2-half': 'styles__u-mt-2-half___3fdSf',
  'u-mb-2-half': 'styles__u-mb-2-half___2ceA7',
  'u-ml-2-half': 'styles__u-ml-2-half___1QHeZ',
  'u-mr-2-half': 'styles__u-mr-2-half___8_Z-H',
  'u-mv-2-half': 'styles__u-mv-2-half___1t_Bp',
  'u-mh-2-half': 'styles__u-mh-2-half___3t7n-',
  'Panel-group': 'styles__Panel-group___1txSp',
  'Panel-main': 'styles__Panel-main___2BRfq',
  'Panel-side': 'styles__Panel-side___327EK'
};
var Group = exports.Group = (0, _utils.mkComponent)('div', { className: styles['Panel-group'] });
var Main = exports.Main = (0, _utils.mkComponent)('div', { className: styles['Panel-main'] });
var Side = exports.Side = (0, _utils.mkComponent)('aside', { className: styles['Panel-side'] });

exports.default = {
  Group: Group,
  Main: Main,
  Side: Side
};